---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: default
  labels:
    app: weblog
    env: study
spec:
  containers:
  - name: debug
    image: tenpei/debug:v1.0.0
    imagePullPolicy:  # hostOS上のイメージを取得する
    command:
    - "sh"
    - "-c"
    args:
    - |
      while true
      do
        sleep 5
      done
